language: node_js
node_js:
  - "0.10"
  - "0.12"
  - iojs
before_script:
  - npm install -g grunt-cli
  - wget "https://s3.amazonaws.com/bitly-downloads/nsq/nsq-0.3.0.linux-amd64.go1.3.3.tar.gz"
  - tar zvxf "nsq-0.3.0.linux-amd64.go1.3.3.tar.gz"
  - export PATH="$PATH:./nsq-0.3.0.linux-amd64.go1.3.3/bin"
